var neurodata = [];

/*neurodata.push({'diabetes':["A 45 year-old Chinese lady with Type II Diabetes Mellitus comes to your clinic with tingling in both hands over 2 months", {"APB": 1, "Opponens Pollicis" : 1, "Finger Abduction" : 1, "Sensation in Hands" : 1, "Reflexes" : 0.5}, {"APB": "Weak", "Opponens Pollicis": "Weak", "Finger Abduction": "Strong", "Pin Prick": "Reduced over 1st 3.5 fingers", "Reflexes": "Normal"}, {"NCS" : 1, "HbA1C" : 0.5, "Thyroid": 0.5}, {"NCS": "Confirmation of Carpal Tunnel Syndrome", "HbA1c": "9%", "Thyroid": "Normal"}, ["Radial Nerve Trauma", "Neurosyphilis", "Gullain-Barre Syndrome", "Median Nerve Trauma"], "Median Nerve Trauma"]});*/

neurodata.push({'bell palsy':[  "A 35 year-old Malay lady who was previously well complains of left-sided face sagging that started a week ago over the morning but is improving steadily. She also mentioned her food tastes different.", {"Facial Expression": 1, "Corneal Reflex": 1, "Otoscopy": 1, "Pronator Drift": 0.5,}, {"Facial Expression": "Both upper and lower parts are weak", "Corneal Reflex" : "Reduced on the left", "Otoscopy": "Normal", "Pronator Drift": "Normal"}, {"NCS": 1}, {"NCS": "Blink Reflex"}, ["Right Hemispheric Stroke", "Bell's Palsy", "Ramsay-Hunt Syndrome"], "Bell's Palsy"]});

neurodata.push({'hemi tumour':["A 50 year-old Eurasian male smoker with a history of HT and DM presents with right-sided weakness that is progressively worsening over 2 months. He keeps bumping into objects on the right and complains of a dull persistent headache.", {"Facial Expression": 1, "Visual Fields": 1, "Fundoscopy" : 0.5, "Pronator Drift": 1, "Shoulder Abduction": 1, "Plantars": 1}, {"Facial Expression": "Mild right-sided weakness, upper face spared", "Visual Fields": "Right homonymous hemianopia", "Fundoscopy": "Mild Papilloedema", "Pronator Drift": "Right Pronator Drift", "Shoulder Abduction": "Mild Right-Sided Weakness", "Plantars": "Upgoing Plantars on the right"}, {"Angio": 1, "CXR" : 1, "MRI": 1}, {"Angio": "Enhancing lesion in the left hemisphere", "CXR": "Normal", "MRI": "Enhancing lesion in the left hemisphere"}, ["Right-sided Stroke", "Left-Sided Stroke", "Left Hemispheric Neoplasm", "Right Hemispheric Neoplasm"], "Left Hemispheric Neoplasm"]});

neurodata.push({'multiple sclerosis':["A 30 year-old Chinese lady presents with right facial weakness over the past 2 days. She also mentions mild numbness over her left arm and leg and double vision when she looks to the right. 3 years ago she had an episode of blurred vision in her right eye.", {"Facial Expression": 1, "Corneal Reflex":1, "Eye Movements":1, "Pronator Drift": 1, "Shoulder Abduction": 1, "Biceps Jerk": 1, "Plantars": 1, "Speech":0.5}, {"Facial Expression": "Right facial weakness, inability to shut right eye.", "Corneal Reflex": "Present on both sides", "Eye Movements":"Looks to the left", "Pronator Drift": "Right-sided", "Shoulder Abduction": "Right-sided weakness", "Biceps Jerk": "Brisk on the right", "Plantars": "Upgoing on the right", "Speech": "Babbles and does not follow commands"}, {"MRI":1, "HbA1c":1, "LDL" : 0.5}, {"MRI": "Hyperintensity and restricted diffusion in left MCA territory", "HbA1c":"9%", "LDL" : "4.3mmol/l"}, ["Left hemispheric stroke", "Systemic Lupus Erythematosus", "Bell's Palsy", "Multiple Sclerosis"], "Multiple Sclerosis"]});

neurodata.push({'bell palsy 2': ["A 60 year-old Indian man comes into the clinic with sudden onset of right-sided weakness. His family mentions that he has been babbling as well. He has a past history of HT, DM and elevated LDL.", {"Facial Expression": 1, "Corneal Reflex":1, "Otoscopy":1, "Pronator Drift": 0.5, "Shoulder Abduction":0.5, "Biceps Jerk": 0.5}, {"Facial Expression": "Mouth sags on the right. Able to close both eyes", "Corneal Reflex": "Reduced on the left", "Otoscopy":"Normal", "Pronator Drift": "Normal", "Shoulder Abduction":"Normal", "Biceps Jerk": "Normal"}, {"NCS":1}, {"NCS": "Blink Reflex"}, ["Bell's Palsy", "Ramsay-Hunt Syndrome", "Left Hemispheric Stroke"], "Bell's Palsy"]});

neurodata.push({'high ulnar neuropathy': ["A 8 year-old boy comes in with progressive clumsiness and weakness of his right hand. He also mentions his ring and little fingers are not as strong as they used to be. He had previously fractured his right elbow 2 years ago.", {"Finger Abduction": 1, "Finger Flexion": 1, "Wartenberg Sign": 1, "Froment's Sign": 1, "Tinel's Test": 1, "Neuronal Pinprick": 1}, {"Finger Abduction": "Weak", "Finger Flexion": "Decreased strength of flexion in 4th and 5th distal interphalangeal joints", "Wartenberg Sign": "Ulnar deviation of little finger in extension", "Froment's Sign": "Flexion of interphalangeal joint", "Tinel's Test": "Shooting sensation down medial aspect of arm", "Neuronal Pinprick": "Decreased sensation over volar and dorsal aspect of medial 1.5 digits."}, {"Nerve Conduction Study": 1}, {"Nerve Conduction Study": "Less rapid down ulnar nerve"}, ["High ulnar nerve lesion", "Low ulnar nerve lesion", "High median nerve lesion"], "High ulnar nerve lesion"]});

neurodata.push({'cts': ["A 45 year-old Chinese lady comes to your clinic with tingling in her left hand that is particularly bad at night. She also complains that she has not been able to use chopsticks to eat for the past 2 weeks. She is currently working as a secretary.", {"Finger Abduction": 1, "Thumb Abduction": 1, "Finger Extension": 1, "Thumb Opposition": 1, "Tinel's Test": 1, "Neuronal Pinprick": 1}, {"Finger Abduction": "Strong", "Thumb Abduction": "Weak", "Finger Extension": "Strong", "Thumb Opposition": "Weak", "Tinel's Test": "Tingling over thenar eminence", "Neuronal Pinprick": "Reduced over lateral 3.5 fingers"}, {"Nerve Conduction Study": 1, "Thyroid Function Test": 0.5, "HbA1c": 0.5}, {"Nerve Conduction Study": "Less rapid down median nerve", "Thyroid Function Test": "Unremarkable", "HbA1c": "6.3%"}, ["Low median nerve lesion", "High median nerve lesion", "Cervical Spondylopathy"], "Low median nerve lesion"]});

neurodata.push({'pin': ["A 23 year-old man comes to the Emergency department after sustaining a deep cut on the outside of his right forearm at work. He complains that he is unable to 'lift' his fingers up.", {"Neuronal Pinprick": 1, "Finger Extension": 1, "Wrist Extension": 1, "Thumb Extension": 1, "Arm Extension": 1, "Dermatomal Pinprick": 1}, {"Neuronal Pinprick": "Unremarkable", "Finger Extension": "Weak", "Wrist Extension": "Strong", "Thumb Extension": "Weak", "Arm Extension": "Strong", "Dermatomal Pinprick": "Unremarkable"}, {"Nerve Conduction Study": 1}, {"Nerve Conduction Study": "Posterior Interosseus Nerve Lesion"}, ["Posterior Interosseus Nerve Lesion", "High radial nerve lesion", "Low radial nerve lesion"], "Posterior Interosseus Nerve Lesion"]});

neurodata.push({'peroneal nerve': ["A 30 year-old Indian yoga exponent comes to the clinic complaining of his left foot dragging.", {"Ankle Dorsiflexion": 1, "Ankle Eversion": 1, "Ankle Inversion": 1, "Ankle Plantarflexion": 1, "Neuronal Pinprick": 1, "Hip Adduction": 1, "Dermatomal Sensation": 0.5, "Straight Leg Raise": 0.5}, {"Ankle Dorsiflexion": "Weak", "Ankle Eversion": "Weak", "Ankle Inversion": "Strong", "Ankle Plantarflexion": "Strong", "Neuronal Pinprick": "Decreased over posterolateral leg", "Hip Adduction": "Strong", "Dermatomal Sensation": "Does not follow dermatomal pattern", "Straight Leg Raise": "Full range of motion"}, {"Nerve Conduction Study": 1, "MRI Lumbosacral Spine": 0.5}, {"Nerve Conduction Study": "Peroneal Nerve Conduction Block at Peroneal Neck", "MRI Lumbosacral Spine": "Unremarkable"}, ["Sciatic Nerve Lesion", "L5 Radiculopathy", "Common Peroneal Nerve Lesion"], "Common Peroneal Nerve Lesion"]});




